
#' Get Network Edges Data
#'
#' This function returns an interactive table of the edges in
#' the network graph.
#'
#' @param artist_id Character string of the search artist's Spotify Id
#'
#' @return table
#' @export
#'
#' @examples
#' related_artists_edges(artist_id = "3fMbdgg4jU18AjLCKBhRSm")

library(spotifyr)
library(dplyr)
library(reactable)
related_artists_edges <- function(artist_id){
  # get artists related to main artist
  related_artists <- get_related_artists(id = artist_id,
                                         include_meta_info = TRUE)

  # get other artists that are related to the
  # artists that are related to the main artist
  other_related <- c()
  for(i in 1:nrow(related_artists$artists)){
    result <- get_related_artists(id = related_artists$artists[["id"]][i],
                                  include_meta_info = TRUE)
    other_related <- append(other_related,result)
  }

  # create edges data.frame
  edges <- data.frame(
    Vertex1 = tolower(c(other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name)),

    Vertex2 = tolower(c(other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[19]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[20]]$name,
                        other_related[[1]]$name,
                        other_related[[2]]$name,
                        other_related[[3]]$name,
                        other_related[[4]]$name,
                        other_related[[5]]$name,
                        other_related[[6]]$name,
                        other_related[[7]]$name,
                        other_related[[8]]$name,
                        other_related[[9]]$name,
                        other_related[[10]]$name,
                        other_related[[11]]$name,
                        other_related[[12]]$name,
                        other_related[[13]]$name,
                        other_related[[14]]$name,
                        other_related[[15]]$name,
                        other_related[[16]]$name,
                        other_related[[17]]$name,
                        other_related[[18]]$name,
                        other_related[[19]]$name))
  )

  # add edge id column and locate in front of data.frame
  edges$id <- 1:nrow(edges)

  edges <- edges |>
    relocate(id)

  edges_table <- reactable(edges,
                           theme = reactableTheme(highlightColor = "#00FFAB",
                                                  borderColor = "#00FFAB"),
                           outlined = T,
                           bordered = T,
                           filterable = T,
                           striped = T,
                           compact = T,
                           highlight = T,
                           defaultColDef = colDef(align = "center",
                                                  headerStyle = list(background = "#00FFAB")),
                           paginationType = "simple")

  return(edges_table)


}









