
#' Get Related Artists Network Graph
#'
#' This function returns an interactive network graph of artists
#' that are related to the search artist.
#'
#' @param artist_id Character string of the search artist's Spotify Id
#'
#' @return network graph
#' @export
#'
#' @examples
#' related_artists_network(artist_id = "3fMbdgg4jU18AjLCKBhRSm")
  related_artists_network <- function(artist_id){
  # get artists related to main artist
  related_artists <- get_related_artists(id = artist_id,
                                         include_meta_info = TRUE)

  # get other artists that are related to the
  # artists that are related to the main artist
  other_related <- c()
  for(i in 1:nrow(related_artists$artists)){
    result <- get_related_artists(id = related_artists$artists[["id"]][i],
                                  include_meta_info = TRUE)
    other_related <- append(other_related,result)
  }

  # create nodes data.frame
  nodes <- data.frame(
    id = c(1:400),

    label = c(other_related[[1]]$name,
              other_related[[2]]$name,
              other_related[[3]]$name,
              other_related[[4]]$name,
              other_related[[5]]$name,
              other_related[[6]]$name,
              other_related[[7]]$name,
              other_related[[8]]$name,
              other_related[[9]]$name,
              other_related[[10]]$name,
              other_related[[11]]$name,
              other_related[[12]]$name,
              other_related[[13]]$name,
              other_related[[14]]$name,
              other_related[[15]]$name,
              other_related[[16]]$name,
              other_related[[17]]$name,
              other_related[[18]]$name,
              other_related[[19]]$name,
              other_related[[20]]$name),

    popularity = c(c(other_related[[1]]$popularity,
                     other_related[[2]]$popularity,
                     other_related[[3]]$popularity,
                     other_related[[4]]$popularity,
                     other_related[[5]]$popularity,
                     other_related[[6]]$popularity,
                     other_related[[7]]$popularity,
                     other_related[[8]]$popularity,
                     other_related[[9]]$popularity,
                     other_related[[10]]$popularity,
                     other_related[[11]]$popularity,
                     other_related[[12]]$popularity,
                     other_related[[13]]$popularity,
                     other_related[[14]]$popularity,
                     other_related[[15]]$popularity,
                     other_related[[16]]$popularity,
                     other_related[[17]]$popularity,
                     other_related[[18]]$popularity,
                     other_related[[19]]$popularity,
                     other_related[[20]]$popularity)),

    followers = c(c(other_related[[1]]$followers.total,
                    other_related[[2]]$followers.total,
                    other_related[[3]]$followers.total,
                    other_related[[4]]$followers.total,
                    other_related[[5]]$followers.total,
                    other_related[[6]]$followers.total,
                    other_related[[7]]$followers.total,
                    other_related[[8]]$followers.total,
                    other_related[[9]]$followers.total,
                    other_related[[10]]$followers.total,
                    other_related[[11]]$followers.total,
                    other_related[[12]]$followers.total,
                    other_related[[13]]$followers.total,
                    other_related[[14]]$followers.total,
                    other_related[[15]]$followers.total,
                    other_related[[16]]$followers.total,
                    other_related[[17]]$followers.total,
                    other_related[[18]]$followers.total,
                    other_related[[19]]$followers.total,
                    other_related[[20]]$followers.total))
  )

  # remove duplicate nodes and labels in data frame
  nodes <- distinct(nodes,label,popularity,followers,.keep_all = T)

  # add node title column and place before 'popularity'
  nodes$title <- paste0("<p>","<b>Artist:</b>"," ",nodes$label,"<br>","<b>Popularity:</b>"," ",
                        nodes$popularity,"<br>","<b>Followers:</b>"," ",nodes$followers,"</br></p>")
  nodes <- nodes |> relocate(title,.before = "popularity")


  # create edges data.frame
  edges <- data.frame(
    from = c(other_related[[1]]$name,
             other_related[[2]]$name,
             other_related[[3]]$name,
             other_related[[4]]$name,
             other_related[[5]]$name,
             other_related[[6]]$name,
             other_related[[7]]$name,
             other_related[[8]]$name,
             other_related[[9]]$name,
             other_related[[10]]$name,
             other_related[[11]]$name,
             other_related[[12]]$name,
             other_related[[13]]$name,
             other_related[[14]]$name,
             other_related[[15]]$name,
             other_related[[16]]$name,
             other_related[[17]]$name,
             other_related[[18]]$name,
             other_related[[19]]$name,
             other_related[[20]]$name),

    to = c(other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[19]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[20]]$name,
           other_related[[1]]$name,
           other_related[[2]]$name,
           other_related[[3]]$name,
           other_related[[4]]$name,
           other_related[[5]]$name,
           other_related[[6]]$name,
           other_related[[7]]$name,
           other_related[[8]]$name,
           other_related[[9]]$name,
           other_related[[10]]$name,
           other_related[[11]]$name,
           other_related[[12]]$name,
           other_related[[13]]$name,
           other_related[[14]]$name,
           other_related[[15]]$name,
           other_related[[16]]$name,
           other_related[[17]]$name,
           other_related[[18]]$name,
           other_related[[19]]$name)
  )

  # add edge id column and locate in front of data.frame
  edges$id <- 1:nrow(edges)

  edges <- edges |>
    relocate(id)

  # re-code the edges data set by nodes id
  for(j in 1:nrow(nodes)){
    edges[edges == nodes[["label"]][j]] <- nodes[["id"]][j]
  }

  # select 1000 edges to render network graph
  edgy <- edges[-c(1001:7600),]

  # create random color selector
  colors <- c("#27AE60","#3498DB","#9B59B6",
              "#566573","#F4D03F","#E74C3C")
  rand_color <- sample(colors,size = 1)


  # render network graph
  spotivis <- visNetwork(nodes = nodes,edges = edgy,width = "100%",height = "650px",
                         main = "Spotify Related Artists Network Graph",
                         footer = paste0("<p><b>","Source: Spotify API","</b></p>")) |>
    visEdges(shadow = TRUE,smooth = F,width = 5,
             color = list(color = "black",highlight = "green")) |>
    visNodes(shape = "dot",
             size = 100,
             borderWidth = 8,
             shadow = list(enabled = T,size = 50),
             color = list(hover = "#85F4FF",
                          border = rand_color),
             title = nodes$title) |>
    visIgraphLayout(layout = "layout_on_sphere") |>
    visInteraction(dragNodes = T,
                   dragView = T,
                   hover = T,
                   selectable = F,
                   navigationButtons = T,
                   tooltipDelay = 0,
                   tooltipStay = 500) |>
    visOptions(nodesIdSelection = F,highlightNearest = F)


  return(spotivis)


}
